# example netlify.toml
# Netlify configuration
[build]
  command = "npm run build"
  publish = "dist"

# Uncomment for Single Page Application (SPA) support
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

# More info: https://ntl.fyi/file-based-build-config
